### ISSUE TITLE
 游戏卡顿 之后按下R游戏画面掉帧，

### ISSUE THREAD

**Issue by q1w2e3dada** [TCreopargh/GreedyCraft#185]
Content: 
    java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Unknown Source)
	at java.util.ArrayList.grow(Unknown Source)
	at java.util.ArrayList.ensureExplicitCapacity(Unknown Source)
	at java.util.ArrayList.ensureCapacityInternal(Unknown Source)
	at java.util.ArrayList.add(Unknown Source)
	at java.util.stream.Collectors$$Lambda$125/553014866.accept(Unknown Source)
	at java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.concurrent.ConcurrentLinkedQueue$CLQSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.jackhuang.hmcl.launch.ExitWaiter.run(ExitWaiter.java:64)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
  Operating System: Windows 10 10.0
  Java Version: 1.8.0_261, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  JVM Max Memory: 3865575424
  JVM Total Memory: 3865575424
  JVM Free Memory: 384070752

**Comment by TCreopargh** [comment]
你内存不够
